---
title: "TSA"
format:
 html:
  code-fold: true
editor:
 render-on-save: true
execute:
  cache: true
---

https://github.com/robjhyndman/fpp3_slides

https://github.com/wch/r-source/blob/trunk/src/library/stats/R/ts.R (arima.sim)

```{r setup, include=FALSE}
library(magrittr)
library(tsibble)
library(feasts)
library(ggplot2)
library(patchwork)
library(latex2exp)
```

```{r, fig.height=4}
set.seed(1)

ar1 <- tsibble(idx = seq_len(100), sim = arima.sim(list(ar = -0.7), n = 100, mean = 10), index = idx)

p1 <- ar1 %>% autoplot(sim) + labs(x = "date", y = "y", title  = TeX("$AR(1): y_{t} = -0.7y_{t-1} + \\epsilon_{t} + 10$"))
p2 <- ar1 %>% ACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "ACF")
p3 <- ar1 %>% PACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "PACF")

p1 / (p2 + p3)
```

```{r, fig.height=4}
set.seed(1)

ar1 <- tsibble(idx = seq_len(100), sim = arima.sim(list(ar = 0.7), n = 100, mean = 10), index = idx)

p1 <- ar1 %>% autoplot(sim) + labs(x = "date", y = "y", title  = TeX("$AR(1): y_{t} = 0.7y_{t-1} + \\epsilon_{t} + 10$"))
p2 <- ar1 %>% ACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "ACF")
p3 <- ar1 %>% PACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "PACF")

p1 / (p2 + p3)
```

```{r, fig.height=4}
set.seed(67)

ar1 <- tsibble(idx = seq_len(100), sim = arima.sim(list(ar = 0.9), n = 100, mean = 10), index = idx)

p1 <- ar1 %>% autoplot(sim) + labs(x = "date", y = "y", title  = TeX("$AR(1): y_{t} = 0.9y_{t-1} + \\epsilon_{t} + 10$"))
p2 <- ar1 %>% ACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "ACF")
p3 <- ar1 %>% PACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "PACF")

p1 / (p2 + p3)
```

```{r, fig.height=4}
set.seed(67)

ar1 <- tsibble(idx = seq_len(100), sim = arima.sim(list(ar = -0.9), n = 100, mean = 10), index = idx)

p1 <- ar1 %>% autoplot(sim) + labs(x = "date", y = "y", title  = TeX("$AR(1): y_{t} = -0.9y_{t-1} + \\epsilon_{t} + 10$"))
p2 <- ar1 %>% ACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "ACF")
p3 <- ar1 %>% PACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "PACF")

p1 / (p2 + p3)
```

```{r, fig.height=4}
set.seed(1)

# If ar > 1 the code will complain that it's not stationary
ar1 <- tsibble(idx = seq_len(100), sim = arima.sim(list(ar = c(0.2, 0.5)), n = 100, mean = 10), index = idx)

p1 <- ar1 %>% autoplot(sim) + labs(x = "date", y = "y", title  = TeX("$AR(2): y_{t} = 0.2y_{t-1} + 0.5y_{t-2} + \\epsilon_{t} + 10$"))
p2 <- ar1 %>% ACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "ACF")
p3 <- ar1 %>% PACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "PACF")

p1 / (p2 + p3)
```

```{r, fig.height=4}
set.seed(1)

# If ar > 1 the code will complain that it's not stationary
ar1 <- tsibble(idx = seq_len(100), sim = arima.sim(list(ar = c(0.2, -0.5)), n = 100, mean = 10), index = idx)

p1 <- ar1 %>% autoplot(sim) + labs(x = "date", y = "y", title  = TeX("$AR(2): y_{t} = 0.2y_{t-1} - 0.5y_{t-2} + \\epsilon_{t} + 10$"))
p2 <- ar1 %>% ACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "ACF")
p3 <- ar1 %>% PACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "PACF")

p1 / (p2 + p3)
```

```{r, fig.height=4}
set.seed(1)

# If ar > 1 the code will complain that it's not stationary
ar1 <- tsibble(idx = seq_len(100), sim = arima.sim(list(ar = c(-0.2, -0.5)), n = 100, mean = 10), index = idx)

p1 <- ar1 %>% autoplot(sim) + labs(x = "date", y = "y", title  = TeX("$AR(2): y_{t} = -0.2y_{t-1} - 0.5y_{t-2} + \\epsilon_{t} + 10$"))
p2 <- ar1 %>% ACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "ACF")
p3 <- ar1 %>% PACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "PACF")

p1 / (p2 + p3)
```

```{r, fig.height=4}
set.seed(1)

# If ar > 1 the code will complain that it's not stationary
ar1 <- tsibble(idx = seq_len(100), sim = arima.sim(list(ar = c(0.5, 0.2)), n = 100, mean = 10), index = idx)

p1 <- ar1 %>% autoplot(sim) + labs(x = "date", y = "y", title  = TeX("$AR(2): y_{t} = 0.5y_{t-1} + 0.2y_{t-2} + \\epsilon_{t} + 10$"))
p2 <- ar1 %>% ACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "ACF")
p3 <- ar1 %>% PACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "PACF")

p1 / (p2 + p3)
```

```{r, fig.height=4}
set.seed(1)

ar1 <- tsibble(idx = seq_len(100), sim = arima.sim(list(ar = c(-0.4, -0.7)), n = 100, mean = 10), index = idx)

p1 <- ar1 %>% autoplot(sim) + labs(x = "date", y = "y", title  = TeX("$AR(2): y_{t} = -0.4y_{t-1} - 0.7y_{t-2} + \\epsilon_{t} + 10$"))
p2 <- ar1 %>% ACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "ACF")
p3 <- ar1 %>% PACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "PACF")

p1 / (p2 + p3)
```

```{r, fig.height=4}
set.seed(1)

ar1 <- tsibble(idx = seq_len(100), sim = arima.sim(list(ar = c(0.4, -0.7)), n = 100, mean = 10), index = idx)

p1 <- ar1 %>% autoplot(sim) + labs(x = "date", y = "y", title  = TeX("$AR(2): y_{t} = 0.4y_{t-1} - 0.7y_{t-2} + \\epsilon_{t} + 10$"))
p2 <- ar1 %>% ACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "ACF")
p3 <- ar1 %>% PACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "PACF")

p1 / (p2 + p3)
```

ar = c(-0.4, 0.7) is not stationary

ar = c(0.4, 0.7) is not stationary

ar = c(0.7, 0.4) is not stationary


```{r, fig.height=4}
set.seed(1)

ar1 <- tsibble(idx = seq_len(100), sim = arima.sim(list(order = c(1, 1, 0), ar = c(0.000000001)), n = 99), index = idx)

p1 <- ar1 %>% autoplot(sim) + labs(x = "date", y = "y", title  = TeX("$AR(1): y_{t} = y_{t-1} + \\epsilon_{t} + 0$"))
p2 <- ar1 %>% ACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "ACF")
p3 <- ar1 %>% PACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "PACF")

p1 / (p2 + p3)
```

```{r, fig.height=4}
set.seed(4)

ar1 <- tsibble(idx = seq_len(100), sim = arima.sim(list(order = c(1, 1, 0), ar = c(0.000000001)), n = 99), index = idx)

p1 <- ar1 %>% autoplot(sim) + labs(x = "date", y = "y", title  = TeX("$AR(1): y_{t} = y_{t-1} + \\epsilon_{t} + 0$"))
p2 <- ar1 %>% ACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "ACF")
p3 <- ar1 %>% PACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "PACF")

p1 / (p2 + p3)
```

```{r, fig.height=4}
set.seed(3)

ar1 <- tsibble(idx = seq_len(100), sim = arima.sim(list(order = c(1, 1, 0), ar = c(0.000000001)), n = 99, mean = -0.2), index = idx)

p1 <- ar1 %>% autoplot(sim) + labs(x = "date", y = "y", title  = TeX("$AR(1): y_{t} = y_{t-1} + \\epsilon_{t} - 0.2$"))
p2 <- ar1 %>% ACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "ACF")
p3 <- ar1 %>% PACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "PACF")

p1 / (p2 + p3)
```

```{r, fig.height=4}
set.seed(6)

ar1 <- tsibble(idx = seq_len(100), sim = arima.sim(list(order = c(1, 1, 0), ar = c(0.5)), n = 99), index = idx)

p1 <- ar1 %>% autoplot(sim) + labs(x = "date", y = "y", title  = TeX("$AR(2): y_{t} = 1.5y_{t-1} + 0.5y_{t-2} + \\epsilon_{t} + 0$"))
p2 <- ar1 %>% ACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "ACF")
p3 <- ar1 %>% PACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "PACF")

p1 / (p2 + p3)
```

```{r, fig.height=4}
set.seed(3)

ar1 <- tsibble(idx = seq_len(100), sim = arima.sim(list(order = c(1, 1, 0), ar = c(0.3)), n = 99), index = idx)

p1 <- ar1 %>% autoplot(sim) + labs(x = "date", y = "y", title  = TeX("$AR(2): y_{t} = 1.3y_{t-1} + 0.3y_{t-2} + \\epsilon_{t} + 0$"))
p2 <- ar1 %>% ACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "ACF")
p3 <- ar1 %>% PACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "PACF")

p1 / (p2 + p3)
```

```{r, fig.height=4}
set.seed(3)

ar1 <- tsibble(idx = seq_len(99), sim = difference(arima.sim(list(order = c(1, 0, 0), ar = c(0.3)), n = 99)), index = idx)

p1 <- ar1 %>% autoplot(sim) + labs(x = "date", y = "y", title  = TeX("$AR(2): y_{t} = 1.3y_{t-1} + 0.3y_{t-2} + \\epsilon_{t} + 0$"))
p2 <- ar1 %>% ACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "ACF")
p3 <- ar1 %>% PACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "PACF")

p1 / (p2 + p3)
```

```{r, fig.height=4}
set.seed(3)

ar1 <- tsibble(idx = seq_len(100), sim = difference(arima.sim(list(order = c(1, 1, 0), ar = c(0.3)), n = 99)), index = idx)

p1 <- ar1 %>% autoplot(sim) + labs(x = "date", y = "y", title  = TeX("$AR(2): y_{t} = 1.3y_{t-1} + 0.3y_{t-2} + \\epsilon_{t} + 0$"))
p2 <- ar1 %>% ACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "ACF")
p3 <- ar1 %>% PACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "PACF")

p1 / (p2 + p3)
```

```{r, fig.height=4}
set.seed(3)

ar1 <- tsibble(idx = seq_len(100), sim = difference(arima.sim(list(order = c(1, 1, 0), ar = c(0.3)), n = 99), differences = 2), index = idx)

p1 <- ar1 %>% autoplot(sim) + labs(x = "date", y = "y", title  = TeX("$AR(2): y_{t} = 1.3y_{t-1} + 0.3y_{t-2} + \\epsilon_{t} + 0$"))
p2 <- ar1 %>% ACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "ACF")
p3 <- ar1 %>% PACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "PACF")

p1 / (p2 + p3)
```

Integrated X times to become stationary

```{r, fig.height=4}
set.seed(1)

ar1 <- tsibble(idx = seq_len(100), sim = difference(arima.sim(list(order = c(1, 0, 0), ar = c(0.3)), n = 100)), index = idx)

p1 <- ar1 %>% autoplot(sim) + labs(x = "date", y = "y")
p2 <- ar1 %>% ACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "ACF")
p3 <- ar1 %>% PACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "PACF")

p1 / (p2 + p3)
```

```{r, fig.height=4}
set.seed(1)

ar1 <- tsibble(idx = seq_len(100), sim = arima.sim(list(order = c(1, 0, 0), ar = c(0.3)), n = 100, innov = difference(rnorm(n = 100))[-1]), index = idx)

p1 <- ar1 %>% autoplot(sim) + labs(x = "date", y = "y")
p2 <- ar1 %>% ACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "ACF")
p3 <- ar1 %>% PACF(sim) %>% autoplot() + labs(x = "lag", y = "", title  = "PACF")

p1 / (p2 + p3)
```

```{r, fig.height=4}
set.seed(5)

ar1 <- tsibble(idx = seq_len(100), sim = arima.sim(list(order = c(10, 0, 0), ar = c(0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.9)), n = 100), index = idx)

p1 <- ar1 %>% autoplot(sim) + labs(x = "date", y = "y", title = 'AR10')
p2 <- ar1 %>% ACF(sim, lag_max = 50) %>% autoplot() + labs(x = "lag", y = "", title  = "ACF")
p3 <- ar1 %>% PACF(sim, lag_max = 50) %>% autoplot() + labs(x = "lag", y = "", title  = "PACF")

p1 / (p2 + p3)
```

```{r, fig.height=4}
set.seed(4)

ar1 <- tsibble(idx = seq_len(100), sim = arima.sim(list(order = c(0, 0, 10), ma = c(0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.9)), n = 100), index = idx)

p1 <- ar1 %>% autoplot(sim) + labs(x = "date", y = "y", title = 'MA10')
p2 <- ar1 %>% ACF(sim, lag_max = 50) %>% autoplot() + labs(x = "lag", y = "", title  = "ACF")
p3 <- ar1 %>% PACF(sim, lag_max = 50) %>% autoplot() + labs(x = "lag", y = "", title  = "PACF")

p1 / (p2 + p3)
```